/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'weinanli' at '12/6/17 1:27 AM' with Gradle 3.0
 *
 * @author weinanli, @date 12/6/17 1:27 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
